### ISSUE TITLE
Word List Tab Query

### ISSUE THREAD

**Issue by sokeeffe-1** [Nuix/Exact-Wordlist-Tab#1]
Hi there,

Is it possible to add another column to the output tab showing the corresponding Document ID's for each word hit?

Appreciate any insight.

Thanks,

Stephen

**Comment by camstillhere** [comment]
Hi @sokeeffe-1 ,
I'll check it out - I'm pretty sure that's a yes but you would probably need to select your Production Set (or you'll get all Document ID's for every production or is that what you were expecting?).

It'd be easy to add the GUID in, Document ID is a little bit of effort but I can see it working.

**Comment by sokeeffe-1** [comment]
Hi Cameron,

I hope all is well.

Appreciate you getting back to me so quickly.

So you mean selecting the production set before running the script, that would be great if so? This would then give me the word list for selected items only, rather than the whole dataset?

If the Document ID is too much effort, I think I can use the GUID to map it back to the document id outside of Nuix.

Thanks again for looking into this, much appreciated.

Kind regards,

Stephen

**Comment by camstillhere** [comment]
As requested @sokeeffe-1 
https://github.com/Nuix/Exact-Wordlist-Tab/releases/tag/1.1

**Comment by sokeeffe-1** [comment]
Cameron,

Many thanks for this, much appreciated.

Stephen







___________________________________
The information contained in this communication is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. It may contain confidential or legally privileged information. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by responding to this email and then delete it from your system. EY is neither liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt.
